# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 374fc355b14db0ba2347197319e21bce90c702cc4176642407f4e9cce30504915948adacca9c92fadb306a48739343c951fe917a6c0906582be7a553d5905261

test:
  secret_key_base: 61ea725d114434073442bc7c96b1663c6fd54e76e51d8a2f48e1d3f83986c5ad77b5831cb1e15993140764e33db022ab53a45cfd16eb7bc02ff076abc9f3fd78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
